name: dynamic_theme_mode
description: A Flutter widget that allows theme mode changing during runtime.
version: 1.0.0
homepage: 'https://github.com/dev-schwarz/dynamic_theme_mode.git'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
